name: "Run clippy"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run clippy
    steps:
      - uses: actions/checkout@v3
      - uses: qernal/github-actions-rust-clippy@v2.0.2
